# This is a basic workflow to help you get started with Actions

name: lint_vet_and_testBuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.6' # The Go version to download (if necessary) and use.
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -d
        go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
              
    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go get golang.org/x/lint/golint
        go vet .
        golint .

    # Run build of the application
    - name: Run build
      run: |
        go generate
        go build --ldflags "-s -w -extldflags '-static' -H windowsgui" -o UpdateChecker.exe
